/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#fff0e9',
        'on-primary': '#ffefec',
        outline: '#7a7673',
        'surface-container-high': '#e8e1dc',
        'on-primary-fixed': '#020000',
        'surface-container': '#eee7e2',
        'on-tertiary-fixed': '#371300',
        'on-error-container': '#510017',
        'inverse-surface': '#100e0c',
        'surface-tint': '#a13925',
        'on-primary-fixed-variant': '#610a00',
        'surface-container-highest': '#e3dbd7',
        'on-secondary-fixed-variant': '#5f28c8',
        'on-background': '#312e2c',
        'tertiary-container': '#fe9e69',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#fcf5f1',
        'primary-container': '#fe7d64',
        'surface-container-low': '#f6efeb',
        'inverse-on-surface': '#a19c99',
        'surface-variant': '#e3dbd7',
        primary: '#a13925',
        'on-tertiary-fixed-variant': '#692b00',
        'on-surface-variant': '#5f5b58',
        'tertiary-dim': '#813c0e',
        background: '#fcf5f1',
        'tertiary-fixed-dim': '#ee915d',
        'on-secondary-fixed': '#40009b',
        'on-secondary-container': '#5517bf',
        'error-container': '#f74b6d',
        'on-secondary': '#f8f0ff',
        'on-primary-container': '#500700',
        surface: '#fcf5f1',
        'on-surface': '#312e2c',
        'secondary-dim': '#5e26c7',
        'primary-dim': '#902d1a',
        'primary-fixed': '#fe7d64',
        'on-error': '#ffefef',
        tertiary: '#904719',
        error: '#b41340',
        secondary: '#6a37d4',
        'secondary-fixed': '#dac9ff',
        'surface-dim': '#dad3ce',
        'primary-fixed-dim': '#ed7158',
        'secondary-container': '#dac9ff',
        'on-tertiary-container': '#5b2400',
        'inverse-primary': '#fe7d64',
        'error-dim': '#a70138',
        'tertiary-fixed': '#fe9e69',
        'outline-variant': '#b2aca9',
        'secondary-fixed-dim': '#ceb9ff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
